### ISSUE TITLE
配置文件应该如何填写

### ISSUE THREAD

**Issue by bobolehe** [Nanomoa/CozeDiscord#1]

**Comment by Nanomoa** [comment]
抱歉，忘记在config.yaml文件中注释了
```yaml
coze_discord_config:
  # 服务器id
  server_id:
  # 对接coze的discord机器人id
  target_bot_id:
  # 默认频道id（目前没有用，相关功能还没实现）
  default_channel_id:
  # 用于转发消息的机器人token（在discord开发者平台中获取）
  bot_token: ""
  # 秘钥，请求时请求头中需要携带的proxy-secret参数的值
  proxy_secret: "nanomoa"
```
